In [5]:
# Dependencies
import pandas as pd

In [6]:
# Store filepath in a variable
dirrahea_deaths = "../sources/dirrahea_deaths.csv"

In [7]:
# Read our Data file with the pandas library
dirrahea_deaths_df = pd.read_csv(dirrahea_deaths)

In [16]:
# Show just the header
dirrahea_deaths_df.head(50)

,Entity,Code,Year,Deaths - Cause: Diarrheal diseases - Risk: Child growth failure - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: No access to handwashing facility - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Suboptimal breastfeeding - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Unsafe water source - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Zinc deficiency - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Low birth weight - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Short gestation - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Unsafe sanitation - Sex: Both - Age: Under 5 (Number),Deaths - Cause: Diarrheal diseases - Risk: Vitamin A deficiency - Sex: Both - Age: Under 5 (Number)
0,Afghanistan,AFG,1990,3048,948,895,3469,23,380,259,2622,276
1,Afghanistan,AFG,1991,3555,1114,1081,4068,29,468,320,3071,320
2,Afghanistan,AFG,1992,4456,1399,1386,5104,40,600,411,3850,397
3,Afghanistan,AFG,1993,6013,1878,1840,6825,61,765,524,5145,537
4,Afghanistan,AFG,1994,6105,1911,1826,6912,71,765,526,5206,545
5,Afghanistan,AFG,1995,7123,2239,2115,8053,95,889,612,6067,644
6,Afghanistan,AFG,1996,7236,2287,2141,8187,111,910,628,6166,661
7,Afghanistan,AFG,1997,8019,2533,2343,9031,143,974,674,6799,738
8,Afghanistan,AFG,1998,8427,2665,2441,9465,169,1008,698,7123,797
9,Afghanistan,AFG,1999,8556,2712,2459,9607,187,1024,711,7224,836
10,Afghanistan,AFG,2000,8543,2724,2441,9624,196,1054,732,7233,853
11,Afghanistan,AFG,2001,8598,2757,2430,9726,198,1093,760,7301,878
12,Afghanistan,AFG,2002,8523,2748,2385,9699,193,1135,790,7268,876
13,Afghanistan,AFG,2003,9387,2986,2420,10544,239,1112,775,7884,960
14,Afghanistan,AFG,2004,9336,2965,2309,10469,251,1079,753,7810,951
15,Afghanistan,AFG,2005,8752,2786,2133,9837,236,1030,719,7323,879
16,Afghanistan,AFG,2006,7843,2495,1898,8810,206,913,638,6538,773
17,Afghanistan,AFG,2007,7019,2229,1729,7907,177,831,582,5856,679
18,Afghanistan,AFG,2008,6175,1962,1597,6993,141,764,535,5164,585
19,Afghanistan,AFG,2009,5453,1731,1484,6197,114,693,486,4555,502
20,Afghanistan,AFG,2010,5097,1609,1440,5790,102,640,449,4232,458
21,Afghanistan,AFG,2011,4726,1491,1403,5377,90,597,419,3906,412
22,Afghanistan,AFG,2012,4412,1393,1375,5029,79,562,395,3629,372
23,Afghanistan,AFG,2013,4416,1385,1401,5010,80,534,375,3589,362
24,Afghanistan,AFG,2014,4242,1326,1386,4806,75,503,353,3417,338
25,Afghanistan,AFG,2015,4053,1265,1356,4598,69,480,338,3238,314
26,Afghanistan,AFG,2016,3952,1227,1316,4483,68,463,327,3142,297
27,Afghanistan,AFG,2017,3908,1209,1290,4437,67,461,325,3095,285
28,Afghanistan,AFG,2018,3345,1031,1099,3807,55,401,283,2641,238
29,Afghanistan,AFG,2019,3139,963,1004,3568,53,368,261,2466,220
30,African Region (WHO),NaN,1990,549571,222483,133565,597092,7392,44943,33823,445187,44402
31,African Region (WHO),NaN,1991,564743,227929,139797,611478,7222,45067,33901,455539,44816
32,African Region (WHO),NaN,1992,555908,223891,136783,600228,6945,43464,32840,447050,43952
33,African Region (WHO),NaN,1993,552128,221856,136396,594652,6698,42616,32259,442679,43242
34,African Region (WHO),NaN,1994,556770,223579,138212,598874,6585,42694,32393,445691,43346
35,African Region (WHO),NaN,1995,552540,221761,137712,593902,6355,42352,32211,442079,42957
36,African Region (WHO),NaN,1996,552885,221677,138324,593495,6193,42133,32090,441670,42663
37,African Region (WHO),NaN,1997,551147,220767,137905,590856,6025,41705,31821,439505,42176
38,African Region (WHO),NaN,1998,549689,219962,137362,588505,5879,41321,31587,437562,41721
39,African Region (WHO),NaN,1999,543969,217437,135287,581816,5673,40741,31186,432442,41555
40,African Region (WHO),NaN,2000,532763,212784,131525,569432,5459,39687,30419,423073,40360
41,African Region (WHO),NaN,2001,523947,209029,129019,559691,5163,38750,29738,415586,39175
42,African Region (WHO),NaN,2002,513550,204447,125592,547568,4883,37210,28581,406139,37738
43,African Region (WHO),NaN,2003,498495,198287,121892,531089,4606,35836,27579,393635,36029
44,African Region (WHO),NaN,2004,484605,192490,118205,515699,4370,34391,26503,381798,34112
45,African Region (WHO),NaN,2005,475440,188407,115263,504831,4176,33139,25564,373557,32553
46,African Region (WHO),NaN,2006,476150,188182,114781,504315,4086,32236,24876,372909,31478
47,African Region (WHO),NaN,2007,465090,183492,111984,491814,3903,30979,23913,363382,29612
48,African Region (WHO),NaN,2008,449414,177363,109231,475477,3661,30025,23196,350800,27539
49,African Region (WHO),NaN,2009,436472,172263,106143,461758,3479,28958,22385,340225,25831

In [18]:
dirrahea_deaths_reduced = dirrahea_deaths_df[["Entity", "Code", "Year", "Deaths - Cause: Diarrheal diseases - Risk: Unsafe water source - Sex: Both - Age: Under 5 (Number)"]]
dirrahea_deaths_reduced.head()

,Entity,Code,Year,Deaths - Cause: Diarrheal diseases - Risk: Unsafe water source - Sex: Both - Age: Under 5 (Number)
0,Afghanistan,AFG,1990,3469
1,Afghanistan,AFG,1991,4068
2,Afghanistan,AFG,1992,5104
3,Afghanistan,AFG,1993,6825
4,Afghanistan,AFG,1994,6912

In [ ]:
'Deaths - Cause: Diarrheal diseases - Risk: Unsafe water source - Sex: Both - Age: Under 5 (Number)'